# Generated by Django 4.1.3 on 2022-11-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioSite', '0005_projects_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='Contact',
        ),
    ]
