# Generated by Django 4.1.3 on 2022-11-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioSite', '0006_rename_index_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='github',
            field=models.URLField(default='www.a.cz'),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin',
            field=models.URLField(default='www.a.cz'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.SmallIntegerField(default=123456789),
        ),
    ]
