# Generated by Django 4.1.2 on 2022-11-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioSite', '0007_contact_email_contact_github_contact_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='my_im',
            field=models.URLField(default='https://cdn.pixabay.com/photo/2022/10/02/15/42/sunrise-7493833_960_720.jpg'),
        ),
    ]
