# Generated by Django 4.1.2 on 2022-11-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioSite', '0008_contact_my_im'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='my_im',
            new_name='my_image',
        ),
    ]
